[platformio]
default_envs = 
	esp32c3

src_dir = .
include_dir = .

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    olikraus/U8g2@^2.36.18
    bblanchon/ArduinoJson@^7.4.3
    WiFi
    
build_flags =
    -Wfatal-errors

[env:esp32c3]
board = esp32-c3-devkitm-1

lib_deps =
	${env.lib_deps}
